"""initial schema

Revision ID: 929c892c1bf1
Revises: 
Create Date: 2026-09-07 11:54:39.540241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '929c892c1bf1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosted_zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), server_default='', nullable=False),
    sa.Column('private_zone', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('record_count', sa.Integer(), server_default='2', nullable=False),
    sa.Column('caller_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dns_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ttl', sa.Integer(), server_default='300', nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['hosted_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dns_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dns_records_zone_id'), ['zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dns_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dns_records_zone_id'))

    op.drop_table('dns_records')
    op.drop_table('hosted_zones')
    # ### end Alembic commands ###
